"use client";
import LeftSide from "@/components/LeftSide";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
import RightSide from "@/components/RightSide";
import BgSwirlVideo from "@/components/bgSwirlVideo";
import { motion } from "framer-motion";
import TextBanner from "@/components/TextBanner";
import About from "@/components/About";
import Services from "@/components/Services";
import Resources from "@/components/Resources";

function Home() {
  return (
    <>
      <Head>
        <title>Drafted</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll ">
        <motion.div>
          <BgSwirlVideo />
        </motion.div>
        <Navbar />

        <div className="relative z-10 w-full h-screen flex flex-col justify-center items-center">
          <TextBanner />
        </div>

        <div className="w-full xl:flex items-center gap-20 justify-between">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.7 }}
            className="hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0"
          >
            <LeftSide />
          </motion.div>

          <div className=" w-full items-center justify-center z-10 ">
            <About />
            <Services />
          </div>

          {/* About*/}
          {/* Services */}
          {/* Resources */}
          {/* Membership */}
          {/* Contact */}
          {/* Footer */}

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.7 }}
            className="hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0"
          >
            <RightSide />
          </motion.div>
        </div>
      </main>
    </>
  );
}
export default Home;
